version: "3"

services:
  database:
    container_name: database_api
    image: postgres:10.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=donjuan
      - POSTGRES_PASSWORD=temqueijonaminhapizzadequeijo
      - POSTGRES_DB=pizza
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    container_name: adonis_api
    build: .
    ports:
      - "8080:8080"
    command: npm run dev
    volumes:
      - ".:/usr/api"
    depends_on:
      - database
    environment:
      - DB_HOST=database

volumes:
  pg_data:
